origin_url: https://rapla.dhbw-karlsruhe.de/rapla?page=ical&user=freudenmann&file=TINF23B1
blocklist:
    - "Entwurf mobiler Applikationen"
    - "STUV-ADA 3 (freiwilliger Zusatz)"
    - "Ethik für Informatiker (WM-A)"
    - "Evolutionäre Algorithmen"
    - "Digitale Forensik  (WMA)"
    - "Web-Services (WM-A)"
    - "Gamification"
    - "Kommunikations und Netztechnik II"
    - "angewandtes Projektmanagement"
    - "Interaktive Systeme (KI & IS)"
    - "Bildverarbeitung (KI & BV)"
    - "Kommunikations und Netztechnik II"
    - "Mobile Applikationen"
    - "Mathematische Grundlagen der Kryptographie"
    - "Grundlagen der KI (KI & BV)"
    - "Grundlagen der KI (KI & IS)"
    - "e Business"
    - "Mathematische Grundlagen der Kryptographie"
